Lab1
linukc/planning pull request #2
Opened 2021-07-15 12:40 UTC by linukc

Сдача лабораторной номер один.
Есть непонятный мне момент - почему с YourOpen последний тест иногда падает в False.

2021-07-15 13:44 UTC, aandreychuk commented
Проблема в методе AddNode.
Во-первых, он отвратителен с точки зрения эффективности работы)) Он использует линейный поиск для обнаружения дубликата и, по сути, используемая куча не имеет преимуществ перед обычным списком.
Во-вторых, при обнаружении дубликата и уменьшении его g- и F-значений ломается структура кучи - у элемента изменился ключ, по которому отсортирована куча, но он остался лежать на том же месте.

2021-07-15 13:47 UTC, aandreychuk requested changes
Нужно переписать AddNode в YourOpen

2021-07-17 07:13 UTC, linukc commented
@aandreychuk переписал через heapq

2021-07-17 07:35 UTC, aandreychuk approved these changes

2021-07-17 07:44 UTC, merged